const express = require('express')
const app = express()
const port = 3000;
const cors = require('cors')
const bodyParser = require('body-parser')
const Personnel_Router = require("./src/Router/personnel.router")
const Rollcall_Router = require("./src/Router/rollcall.router")
const Location_Router = require("./src/Router/location.router")
const Mac_Address_Router = require("./src/Router/mac_address.router")
const QR_Code_Router = require("./src/Router/qr_code.router")
const Notification_Router = require("./src/Router/notification.router")
const Break_Time_Router = require("./src/Router/break_time.router")
const Auth_Middleware = require("./src/Auth/authmiddleware")
const router = express.Router()
const Personnel_Controller = require("./src/Controller/personnel.controller")
// const firebase =require("./src/Common/firebase")
app.use(cors())
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())


router.post("/register",Personnel_Controller.create_Personnel)
router.post("/login-personnel",Personnel_Controller.login_Personnel)
app.use("/public/api",router)
app.use(Auth_Middleware.is_Auth)
app.use("/public/api",Personnel_Router,)
app.use("/public/api",Notification_Router)
app.use("/public/api",Rollcall_Router)
app.use("/public/api",Location_Router)
app.use("/public/api",Mac_Address_Router)
app.use("/public/api",QR_Code_Router)
app.use("/public/api",Break_Time_Router)
app.listen(port,function(){
  console.log("server start on :",port)
})


